### ISSUE TITLE
Call creation hook requests do not include authorization header

### ISSUE THREAD

**Issue by AFelix53** [jambonz/jambonz-feature-server#112]
When creating a call via REST request, the requests sent to the hooks defined on the `call_hook`  and `call_status_hook` are not including the authorization header with the basic auth parameters.

```javascript
 jambonzClient.calls.create({
                call_hook,
                call_status_hook,
                from,
                to: {
                    type: 'phone',
                    number,
                },
            });
 ```
            
Requests to the `call_hook` or `call_status_hook` include the following headers only:

```
{
  host: 'XXXX-XXX-XXX-100-197.ngrok.io',
  'content-length': '279',
  'accept-encoding': 'br, gzip, deflate',
  'content-type': 'application/json',
  'jambonz-signature': 't=1654013953,v1=7dac24e1bxxxxxxxxxxx0b0a08fc0280f8b1',
  'x-forwarded-for': 'XX.XX.XXX.XXX',
  'x-forwarded-proto': 'https'
}
```

**Comment by AFelix53** [comment]
Yes, all other hook requests use the username/password defined on the jambonz Application to build the 
`Authorization: Basic XXXXXXXXXXXX` header.

**Comment by davehorton** [comment]
OK, well that is provisioned with your application.  So instead of providing a call_hook in your createCall payload, use the format where you specify the application_sid.  You will of course need to have defined the application with the call hook url and the basic auth params.

See [here](https://api.jambonz.org/#243a2edd-7999-41db-bd0d-08082bbab401) for an example of what I am talking about

**Comment by davehorton** [comment]
My comment above (providing an application_sid in the POST request, rather than call_hook url) is really a workaround.  A proper fix would allow someone to specify a call_hook (and call_status_hook) that included a username and password which would then be used for HTTP basic auth.  

We can see that the current swagger doc supports this:

[createCall ](https://github.com/jambonz/jambonz-api-server/blob/6f52202debd327c0b36a6b82c8336f097219f253/lib/swagger/swagger.yaml#L2956) includes call_hook which is a Webhook

[Webhook](https://github.com/jambonz/jambonz-api-server/blob/6f52202debd327c0b36a6b82c8336f097219f253/lib/swagger/swagger.yaml#L3525) includes optional username and password

We just need to implement that (I think)

**Comment by xquanluu** [comment]
I start contributing to this issue

**Comment by xquanluu** [comment]
Hi @davehorton  @AFelix53 

The jambonz server call_hoook is already supported username and password for basic authentication:

post('v1/createCall', {
      'account_sid':account_sid,
      "call_hook": {
        "url": "https://webhook.site/503a5d06-c057-4864-9812-ea36b5f0eb44",
        "method": "POST",
        "username": "username",
        "password": "password"
      },
      "from": "15083718299",
      "to": {
        "type": "phone",
        "number": "15583084809"
      }})

This will let jambonz server create basic auth Http header

This is another issue with documentation is not mentioning about this ability from call_hook

**Comment by xquanluu** [comment]
this is fixed and merged
