### ISSUE TITLE
Can not add carriers with arm chrome on new marketplace v8

### ISSUE THREAD

**Issue by timmeade** [jambonz/jambonz-feature-server#273]
Adding Carrier to new aws marketplace.

Upgrade to SSL. per instructions 

When adding carrier using Chrome
```
Version 110.0.5481.177 (Official Build) (arm64)
```

Nothing happens on save.  Console shows:

```
An invalid form control with name='sip_username' is not focusable. 
<input id="sip_username" name="sip_username" type="text" placeholder="SIP username for authenticating outbound calls" value required>
```

Tried exact same procedure on safari 
```
Version 16.3 (18614.4.6.1.6)
```
Works fine.

**Comment by davehorton** [comment]
Can you close this issue here and open it under jambonz-webappSent from my iPhoneOn Mar 2, 2023, at 5:09 PM, Tim Meade ***@***.***> wrote:﻿
Adding Carrier to new aws marketplace.
Upgrade to SSL. per instructions
When adding carrier using Chrome
Version 110.0.5481.177 (Official Build) (arm64)

Nothing happens on save.  Console shows:
An invalid form control with name='sip_username' is not focusable. 
<input id="sip_username" name="sip_username" type="text" placeholder="SIP username for authenticating outbound calls" value required>

Tried exact same procedure on safari
Version 16.3 (18614.4.6.1.6)

Works fine.

**Comment by timmeade** [comment]
Moving per dave
