### ISSUE TITLE
custom speech vendor support for transcribe

### ISSUE THREAD

**Issue by vasudevan-Kore** [jambonz/jambonz-feature-server#388]
Have observed the following error for custom speech vendor in case of transcribe hook invoke internally on dial. The _startTranscribing method does not seem to support custom speech vendor. Here is the error : 

Error: Invalid vendor custom:xxxxxx
9|jambonz-feature-server  |     at TaskTranscribe._startTranscribing (/home/admin/apps/jambonz-feature-server/lib/tasks/transcribe.js:237:15)
9|jambonz-feature-server  |     at TaskTranscribe.exec (/home/admin/apps/jambonz-feature-server/lib/tasks/transcribe.js:126:18)
9|jambonz-feature-server  |     at TaskDial._selectSingleDial (/home/admin/apps/jambonz-feature-server/lib/tasks/dial.js:671:50)
9|jambonz-feature-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
9|jambonz-feature-server  |     at async TaskDial._connectSingleDial (/home/admin/apps/jambonz-feature-server/lib/tasks/dial.js:614:5)
9|jambonz-feature-server  |     at async SingleDialer.<anonymous> (/home/admin/apps/jambonz-feature-server/lib/tasks/dial.js:562:15)

**Comment by davehorton** [comment]
@vasudevan-Kore can you test the PR above?

**Comment by vasudevan-Kore** [comment]
Hi @vasudevan-Kore the issue still seems to persists

**Comment by davehorton** [comment]
@xquanluu can you test on our system with one of our custom speech implementations?

**Comment by davehorton** [comment]
@xquanluu any status?

**Comment by davehorton** [comment]
@xquanluu can you recreate?

**Comment by xquanluu** [comment]
The issue is the ws far end close the connection:

bbbe9a7c-e9bc-44aa-822c-11c67a71f3c4 2023-08-25 11:15:16.151187 [INFO] jb_transcribe_glue.cpp:177 connection successful
bbbe9a7c-e9bc-44aa-822c-11c67a71f3c4 2023-08-25 11:15:16.171188 [DEBUG] switch_core_io.c:448 Setting BUG Codec PCMU:0
1e6458fe-fbc6-493c-a348-4b7fbb7af544 2023-08-25 11:15:16.472095 [DEBUG] switch_rtp.c:7759 Correct audio ip/port confirmed.
bbbe9a7c-e9bc-44aa-822c-11c67a71f3c4 2023-08-25 11:15:26.151189 [DEBUG] jb_transcribe_glue.cpp:195 connection dropped from far end
