### ISSUE TITLE
feat: Dial verb to have Info actionhook

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#471]
Dial verb to have action that handles INFO packet. this will help to forward the packet to source or take any action

**Comment by vdharashive** [comment]
Info packet can be originated from webrtc client as well

**Comment by davehorton** [comment]
can you provide an example use case where this is needed?

**Comment by davehorton** [comment]
I think rather than putting this in the dial verb we should have it in the config verb.  Its not only when on a dial that you could get an incoming INFO message, it could happen while simply connected to a voicebot as well.  Therefore it makes more sense for it to be a config verb property.

Secondly, I think we should handle some other in-dialog requests as well; minimally the MESSAGE message.  I think for now not SUBSCRIBE or NOTIFY as those bring in a lot more feature functionality and we may want to design separately for those.

**Comment by vdharashive** [comment]
@davehorton config verb for INFO also will work rather then dial

**Comment by vdharashive** [comment]
@davehorton , @xquanluu 

wss client send request of info , which is received in sbc-inbound , there needs to be implementation to forward this message feature server 

{
  "level": 30,
  "time": "2023-10-08T12:33:33.451Z",
  "pid": 137400,
  "hostname": "ip-172-31-10-85",
  "callId": "0c5df13156ded6d72e4da90b577c8803@0.0.0.0",
  "err": {
    "type": "Error",
    "message": "Server error: unable to find dialog for dialog id provided",
    "stack": "Error: Server error: unable to find dialog for dialog id provided\n    at DrachtioAgent.<anonymous> (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/drachtio-agent.js:315:21)\n    at DrachtioAgent._onMsg (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/drachtio-agent.js:733:11)\n    at WireProtocol.emit (node:events:513:28)\n    at WireProtocol.processMessageBuffer (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/wire-protocol.js:293:12)\n    at WireProtocol._onData (/home/admin/apps/sbc-inbound/node_modules/drachtio-srf/lib/wire-protocol.js:326:14)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:293:11)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
  },
  "msg": "Error handing INFO request on uac leg"
}
