### ISSUE TITLE
Feat : Handling Refer for outbound call 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/jambonz-feature-server#504]
on making outbound call from webrtc client the sipdevice handler makes outbound call to telephone number and bridges the call 

then the webrtc client needs to do the refer to handover dailer number to the bot , but after accepting the refer the webrtc client send bye and both calls are hangup. 

hence there need to be a way in which dialer number call need not hangup ever caller webrtc client hangup the call

**Comment by davehorton** [comment]
please send feature server logs privately

**Comment by davehorton** [comment]
please test the `fix/refer-from-caller` branch.  The way this is resolved is to allow you to return a payload from the referHook.  Previously, any returned payload was ignored.  Now, you can optionally return an array of jambonz verbs, and these will be executed on the other call leg -- e.g. if you get a REFER on the A leg you return the application you want to execute on the B leg.  

This eliminates the race condition that was causing this issue (and probably simplifies your code as well, since you now no longer have to respond to the referHook and then do something separate like an LCC command)
